# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_with_QTDesign_Webcam.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(60, 70, 89, 25))
        icon = QtGui.QIcon.fromTheme("arrow")
        self.leftButton.setIcon(icon)
        self.leftButton.setObjectName("leftButton")
        self.DXspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.DXspinBox.setGeometry(QtCore.QRect(370, 50, 48, 26))
        self.DXspinBox.setMaximum(20)
        self.DXspinBox.setObjectName("DXspinBox")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(160, 70, 89, 25))
        self.rightButton.setObjectName("rightButton")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(110, 40, 89, 25))
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(110, 100, 89, 25))
        self.downButton.setObjectName("downButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 90, 71, 20))
        self.label_2.setObjectName("label_2")
        self.DYspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.DYspinBox.setGeometry(QtCore.QRect(370, 90, 48, 26))
        self.DYspinBox.setMaximum(20)
        self.DYspinBox.setObjectName("DYspinBox")
        self.buttonQUIT = QtWidgets.QPushButton(self.centralwidget)
        self.buttonQUIT.setGeometry(QtCore.QRect(120, 160, 61, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonQUIT.setFont(font)
        self.buttonQUIT.setObjectName("buttonQUIT")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 50, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 90, 71, 20))
        self.label_4.setObjectName("label_4")
        self.XspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.XspinBox.setGeometry(QtCore.QRect(520, 50, 51, 26))
        self.XspinBox.setMaximum(20)
        self.XspinBox.setObjectName("XspinBox")
        self.YspinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.YspinBox.setGeometry(QtCore.QRect(520, 90, 51, 26))
        self.YspinBox.setMaximum(20)
        self.YspinBox.setObjectName("YspinBox")
        self.CMxPos = QtWidgets.QLineEdit(self.centralwidget)
        self.CMxPos.setGeometry(QtCore.QRect(370, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CMxPos.setFont(font)
        self.CMxPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CMxPos.setReadOnly(True)
        self.CMxPos.setObjectName("CMxPos")
        self.CMyPos = QtWidgets.QLineEdit(self.centralwidget)
        self.CMyPos.setGeometry(QtCore.QRect(370, 190, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CMyPos.setFont(font)
        self.CMyPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CMyPos.setReadOnly(True)
        self.CMyPos.setObjectName("CMyPos")
        self.XposLabel = QtWidgets.QLabel(self.centralwidget)
        self.XposLabel.setGeometry(QtCore.QRect(290, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.XposLabel.setFont(font)
        self.XposLabel.setObjectName("XposLabel")
        self.YposLabel = QtWidgets.QLabel(self.centralwidget)
        self.YposLabel.setGeometry(QtCore.QRect(290, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YposLabel.setFont(font)
        self.YposLabel.setObjectName("YposLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.leftButton.setText(_translate("MainWindow", "Left"))
        self.rightButton.setText(_translate("MainWindow", "Right"))
        self.upButton.setText(_translate("MainWindow", "Up"))
        self.downButton.setText(_translate("MainWindow", "Down"))
        self.label.setText(_translate("MainWindow", "X stepsize:"))
        self.label_2.setText(_translate("MainWindow", "Y stepsize:"))
        self.buttonQUIT.setText(_translate("MainWindow", "QUIT"))
        self.label_3.setText(_translate("MainWindow", "X center:"))
        self.label_4.setText(_translate("MainWindow", "Y center:"))
        self.CMxPos.setText(_translate("MainWindow", "131"))
        self.CMyPos.setText(_translate("MainWindow", "131"))
        self.XposLabel.setText(_translate("MainWindow", "X pos:"))
        self.YposLabel.setText(_translate("MainWindow", "Y pos:"))

