# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_with_QTDesign_Webcam_2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 443)
        self.CMyPos = QtWidgets.QLineEdit(Form)
        self.CMyPos.setGeometry(QtCore.QRect(370, 190, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CMyPos.setFont(font)
        self.CMyPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CMyPos.setReadOnly(True)
        self.CMyPos.setObjectName("CMyPos")
        self.DYlabel = QtWidgets.QLabel(Form)
        self.DYlabel.setGeometry(QtCore.QRect(290, 90, 71, 20))
        self.DYlabel.setObjectName("DYlabel")
        self.XspinBox = QtWidgets.QSpinBox(Form)
        self.XspinBox.setGeometry(QtCore.QRect(520, 50, 51, 26))
        self.XspinBox.setMaximum(20)
        self.XspinBox.setObjectName("XspinBox")
        self.downButton = QtWidgets.QPushButton(Form)
        self.downButton.setGeometry(QtCore.QRect(110, 100, 89, 25))
        self.downButton.setObjectName("downButton")
        self.DXspinBox = QtWidgets.QSpinBox(Form)
        self.DXspinBox.setGeometry(QtCore.QRect(370, 50, 48, 26))
        self.DXspinBox.setMaximum(20)
        self.DXspinBox.setObjectName("DXspinBox")
        self.rightButton = QtWidgets.QPushButton(Form)
        self.rightButton.setGeometry(QtCore.QRect(160, 70, 89, 25))
        self.rightButton.setObjectName("rightButton")
        self.Ylabel = QtWidgets.QLabel(Form)
        self.Ylabel.setGeometry(QtCore.QRect(450, 90, 71, 20))
        self.Ylabel.setObjectName("Ylabel")
        self.YspinBox = QtWidgets.QSpinBox(Form)
        self.YspinBox.setGeometry(QtCore.QRect(520, 90, 51, 26))
        self.YspinBox.setMaximum(20)
        self.YspinBox.setObjectName("YspinBox")
        self.buttonQUIT = QtWidgets.QPushButton(Form)
        self.buttonQUIT.setGeometry(QtCore.QRect(120, 160, 61, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonQUIT.setFont(font)
        self.buttonQUIT.setObjectName("buttonQUIT")
        self.leftButton = QtWidgets.QPushButton(Form)
        self.leftButton.setGeometry(QtCore.QRect(60, 70, 89, 25))
        icon = QtGui.QIcon.fromTheme("arrow")
        self.leftButton.setIcon(icon)
        self.leftButton.setObjectName("leftButton")
        self.Xlabel = QtWidgets.QLabel(Form)
        self.Xlabel.setGeometry(QtCore.QRect(450, 50, 71, 20))
        self.Xlabel.setObjectName("Xlabel")
        self.XposLabel = QtWidgets.QLabel(Form)
        self.XposLabel.setGeometry(QtCore.QRect(290, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.XposLabel.setFont(font)
        self.XposLabel.setObjectName("XposLabel")
        self.CMxPos = QtWidgets.QLineEdit(Form)
        self.CMxPos.setGeometry(QtCore.QRect(370, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.CMxPos.setFont(font)
        self.CMxPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CMxPos.setReadOnly(True)
        self.CMxPos.setObjectName("CMxPos")
        self.DXlabel = QtWidgets.QLabel(Form)
        self.DXlabel.setGeometry(QtCore.QRect(290, 50, 71, 20))
        self.DXlabel.setObjectName("DXlabel")
        self.upButton = QtWidgets.QPushButton(Form)
        self.upButton.setGeometry(QtCore.QRect(110, 40, 89, 25))
        self.upButton.setObjectName("upButton")
        self.DYspinBox = QtWidgets.QSpinBox(Form)
        self.DYspinBox.setGeometry(QtCore.QRect(370, 90, 48, 26))
        self.DYspinBox.setMaximum(20)
        self.DYspinBox.setObjectName("DYspinBox")
        self.YposLabel = QtWidgets.QLabel(Form)
        self.YposLabel.setGeometry(QtCore.QRect(290, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.YposLabel.setFont(font)
        self.YposLabel.setObjectName("YposLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CMyPos.setText(_translate("Form", "131"))
        self.DYlabel.setText(_translate("Form", "Y stepsize:"))
        self.downButton.setText(_translate("Form", "Down"))
        self.rightButton.setText(_translate("Form", "Right"))
        self.Ylabel.setText(_translate("Form", "Y center:"))
        self.buttonQUIT.setText(_translate("Form", "QUIT"))
        self.leftButton.setText(_translate("Form", "Left"))
        self.Xlabel.setText(_translate("Form", "X center:"))
        self.XposLabel.setText(_translate("Form", "X pos:"))
        self.CMxPos.setText(_translate("Form", "131"))
        self.DXlabel.setText(_translate("Form", "X stepsize:"))
        self.upButton.setText(_translate("Form", "Up"))
        self.YposLabel.setText(_translate("Form", "Y pos:"))

